logging.level:
  com.serversquad.polytech.mailapp.mailapp: DEBUG

# list of profiles: local,firebase
spring.profiles.active: firebase


mail.xsd.url: https://rcassier.myds.me/polytech_app5/xm_mail/xm-mail_0.2.1.xsd
mail.messages.body.format.list: https://rcassier.myds.me/polytech_app5/xm_mail/extensions/string.xsd, https://rcassier.myds.me/polytech_app5/xm_mail/extensions/polytech.xsd