local.storage:
  mails.root:
    in.path: /home/nelson/Téléchargements/emailServerStorage/in/mail
    out.path: /home/nelson/Téléchargements/emailServerStorage/in/mail
  bodies.root:
    in.path: /home/nelson/Téléchargements/emailServerStorage/in/body
    out.path: /home/nelson/Téléchargements/emailServerStorage/in/body

test.tes: yuuu