logging.level:
  com.serversquad.polytech.mailapp.mailapp: DEBUG

# list of profiles: local,firebase
spring.profiles.active: firebase

mail.messages.body.format.list: https://rcassier.myds.me/polytech_app5/xm_mail/extensions/string.xsd, https://rcassier.myds.me/polytech_app5/xm_mail/extensions/polytech.xsd